### ISSUE TITLE
Need more doc

### ISSUE THREAD

**Issue by bobmayuze** [tianbot/yy_drone#1]
It'd be great if we can have this in the readme
# Step 1: Download the repo
```
$ git clone https://github.com/tianbot/yy_drone
```

# Step 2: Start ROSCORE
```
$ roscore
```

# Step 3: Launch the sim drone
```
$ roslaunch ./yy_drone/sim_drone/launch/test_kaka.launch
```

**Comment by tianb03** [comment]
quick steps added
